### PR TITLE
Draft normalization 

### PR DESCRIPTION
**Pull request by philouail**
So here is a first draft on the norm for the end to end. 

I'd like to discuss some of the results next week maybe. Especially the plots for the linear model.  
Especially on which between sample method to choose. 
I also wanna be sure that I did not make mistakes with some of the code. especially for the within batch norm, as the results look weird (increase of some CV..) 

So yeah, here looking more for overall feedback and big mistakes so that I don't try to interpret wrong results.

### CODE REVIEW

**Comment by philouail** [comment]
So I pulled the full end to end that has the normalization part with only the selected code, I haven't deleted any of the evaluation part yet because I am actually not sure what to keep and what not to keep.
Also pushed the changes on the whole normalisation file so we keep a trace of it. 

As a note, the alignment is not really that good for methionine IS. maybe we can discuss that.

**Comment by jorainer** [comment]
Thanks! I will merge this into my branch and then eventually come back with a PR to your branch.

**Comment by philouail** [comment]
Hi so I made the updates talked about. I think for now it might be good to merge so that we have a good base and the next PR will be filtering and differential abundance analysis detection. If you see any stuff I forgot to change tell me , i've read it so many time that i might be missing something.

**Review by jorainer — APPROVED** [review]
All good from my side, thanks!

**Pull request merged**
